# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/austi/OneDrive/Desktop/385Labs/final_proj/lab6/lab6.srcs/sources_1/ip/flappystart_rom/flappystart_rom.xci
# IP: The module: 'flappystart_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/austi/OneDrive/Desktop/385Labs/final_proj/lab6/lab6.gen/sources_1/ip/flappystart_rom/flappystart_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flappystart_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/austi/OneDrive/Desktop/385Labs/final_proj/lab6/lab6.srcs/sources_1/ip/flappystart_rom/flappystart_rom.xci
# IP: The module: 'flappystart_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/austi/OneDrive/Desktop/385Labs/final_proj/lab6/lab6.gen/sources_1/ip/flappystart_rom/flappystart_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'flappystart_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
